#!/bin/bash
# system_info.sh - Session 03 homework: print system information,
# take user input and save running processes to a file.
# Author: Poorav Kumar Gupta (24bcs10080)

# ---------- variables ----------
current_date=$(date)
host_name=$(hostname)
user_name=$(whoami)
separator="=============================================="

echo "$separator"
echo "         SYSTEM INFORMATION REPORT"
echo "$separator"

# ---------- system info ----------
echo "Current date : $current_date"
echo "Hostname     : $host_name"
echo "Username     : $user_name"
echo
echo "---------- Disk usage (df -h) ----------"
df -h
echo
echo "---------- Running processes (ps) ----------"
ps -e -o pid,user,%cpu,%mem,comm | head -15
echo

# ---------- user input ----------
read -r -p "Enter your name: " name
read -r -p "Enter your roll number: " roll_no
read -r -p "Enter a directory name to create: " dir_name
read -r -p "Enter a file name to create inside it: " file_name

echo
echo "Hello $name (Roll No: $roll_no)!"

# ---------- create directory and file ----------
mkdir -p "$dir_name"
echo "Directory '$dir_name' created."

touch "$dir_name/$file_name"
echo "File '$dir_name/$file_name' created."

# ---------- store running processes using > redirection ----------
ps aux > "$dir_name/$file_name"
echo "Running processes saved to '$dir_name/$file_name' ($(wc -l < "$dir_name/$file_name") lines)."

echo "$separator"
echo "Report generated by $user_name on $host_name at $current_date"
echo "$separator"
