apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: s12-config
data:
  APP_NAME: "yatri-backend"
  APP_ENV: "staging"
  LOG_LEVEL: "debug"
  MAX_CONNECTIONS: "50"
  app.properties: |
    feature.newCheckout=true
    cache.ttl.seconds=300
    ui.theme=dark
