apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-html
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  index.html: |
    <html><body style="font-family:sans-serif;background:{{ .Values.page.color }};color:white;text-align:center;padding-top:80px">
    <h1>{{ .Values.page.message }}</h1>
    <h2>Release: {{ .Release.Name }} | Revision: {{ .Release.Revision }} | Image: {{ .Values.image.repository }}:{{ .Values.image.tag }}</h2>
    <p>Session 15 Helm homework - Poorav Kumar Gupta (24bcs10080)</p>
    </body></html>
