apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  namespace: s17-devsecops
  labels:
    app: devsecops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: __IMAGE__            # set by the pipeline to registry/s17-devsecops:<git-sha>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 192Mi
      volumes:
        - name: tmp
          emptyDir: {}
